116 condition mapper
bzkf/obds-to-fhir pull request #156
Opened 2024-11-11 13:52 UTC by cfischer27

2024-11-14 08:37 UTC, chgl requested changes

2024-11-14 08:37 UTC, chgl commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/ConditionMapper.java
> +                  "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/CodeSystem/mii-cs-onko-primaertumor-diagnosesicherung",
@pcvolkmer hat in https://github.com/bzkf/obds-to-fhir/pull/157 noch das system hier als property ergänzt - wenn du noch auf beta rebased oder beta in deinen branch mergst kannst du das system auch analog wie in L74 nutzen.

2024-11-14 15:02 UTC, cfischer27 commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/ConditionMapper.java
> +                  "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/CodeSystem/mii-cs-onko-primaertumor-diagnosesicherung",
habe ich noch eingebaut. Jetzt sollten keine direkten URLs mehr drin stehen

2024-11-18 13:39 UTC, chgl requested changes

2024-11-18 13:39 UTC, chgl commented on src/main/resources/application.yml
> +    icdo3Morphologie: "http://terminology.hl7.org/CodeSystem/icd-o-3"
Das problem im snapshot test ist gerade noch, dass in den bisherigen DKTK Profilversionen das icdo3 system als OID fest-kodiert war. Die einfachste Lösung wäre wahrscheinlich erstmal ein neues property hier einfügen 

```suggestion
    icdo3Morphologie: "http://terminology.hl7.org/CodeSystem/icd-o-3"
    icdo3MorphologieOid: "urn:oid:2.16.840.1.113883.6.43.1"
```

und das dann in https://github.com/bzkf/obds-to-fhir/blob/63fe5cc233526f40e4d005fc1a59bc2687fc5c5f/src/main/java/org/miracum/streams/ume/obdstofhir/mapper/ObdsObservationMapper.java#L541 setzen. Dann sollten die snapshots unverändert bleiben.

2024-11-19 10:28 UTC, chgl approved these changes

2024-11-19 10:54 UTC, merged