feat: implement fernmetastasen mapper
bzkf/obds-to-fhir pull request #159
Opened 2024-11-19 09:28 UTC by cfischer27

2024-11-27 09:55 UTC, jasminziegler commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/FernmetastasenMapper.java
> +            meldung.getDiagnose() != null ? meldung.getDiagnose().getMengeFM() : null,
könnten wir in den Observations noch einfügen woraus die Observation entstanden ist (Diagnose oder Verlauf)?

2024-11-28 14:09 UTC, cfischer27 commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/FernmetastasenMapper.java
> +            meldung.getDiagnose() != null ? meldung.getDiagnose().getMengeFM() : null,
habe ich als Identifier eingefügt. Der Identifier besteht aus dem Ort (Diagnose oder Verlauf) und einer fortlaufenden Nummer, der die Fernmetastasen zählt

2024-11-29 14:35 UTC, chgl commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/FernmetastasenMapper.java
> +          int id = 0;
Es fehlt noch ein id++ irgendwo

2024-12-03 09:09 UTC, cfischer27 commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/FernmetastasenMapper.java
> +          int id = 0;
das steht in Zeile 65, nachdem der Identifier gesetzt wurde

2025-01-07 13:51 UTC, chgl requested changes

2025-01-07 13:51 UTC, chgl commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/FernmetastasenMapper.java
> +            observation.addIdentifier(identifier);
observation.setId() noch und ggf observation.addFocus() - auf die condition reference, ansonsten perfekt!

2025-01-14 13:59 UTC, chgl commented on src/main/resources/application.yml
> +    fernmetastasen-id: "${fhir.default.baseSystemUrl}/obds-to-fhir/identifiers/fernmetatasen-id"
```suggestion
    fernmetastasen-id: "${fhir.default.baseSystemUrl}/obds-to-fhir/identifiers/fernmetastasen-id"
```

2025-01-14 14:00 UTC, chgl commented on src/main/resources/application.yml
> +    mii-cs-onko-Fernmetastasen: "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/CodeSystem/mii-cs-onko-fernmetastasen"
```suggestion
    mii-cs-onko-fernmetastasen: "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/CodeSystem/mii-cs-onko-fernmetastasen"
```

2025-01-14 14:33 UTC, cfischer27 commented on src/main/resources/application.yml
> +    fernmetastasen-id: "${fhir.default.baseSystemUrl}/obds-to-fhir/identifiers/fernmetatasen-id"
ist geändert

2025-01-14 14:33 UTC, cfischer27 commented on src/main/resources/application.yml
> +    mii-cs-onko-Fernmetastasen: "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/CodeSystem/mii-cs-onko-fernmetastasen"
ist geändert

2025-01-14 14:40 UTC, chgl approved these changes

2025-01-14 14:40 UTC, merged