feat: add initial SystemischeTherapieMapper
bzkf/obds-to-fhir pull request #165
Opened 2024-11-20 14:20 UTC by pcvolkmer

2024-11-20 16:07 UTC, pcvolkmer commented
As of now, all required fhir elements are present in mapped fhir resources. Optional elements may follow as required by BZKF.

2024-11-20 16:31 UTC, chgl requested changes

2024-11-20 16:31 UTC, chgl commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/SystemischeTherapieMapper.java
> +      var performedStart = new DateTimeType();
Nachdem das Datum maximal tagesgenau sein kann (https://github.com/bzkf/obds-to-fhir/blob/beta/src/main/resources/schema/oBDS_v3.0.3.xsd#L5316) wäre es geschickt hier noch `convertObdsDatumToDateTimeType` einzubauen (kann ich auch flott übernehmen) https://github.com/bzkf/obds-to-fhir/blob/beta/src/main/java/org/miracum/streams/ume/obdstofhir/mapper/ObdsToFhirMapper.java#L254 - dann sparen wir uns auch wieder die zeitstempel und zeitzonen problematik in den snapshots.

2024-11-20 16:36 UTC, chgl requested changes

2024-11-20 16:36 UTC, chgl commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/SystemischeTherapieMapper.java
> +                fhirProperties.getSystems().getSnomed(), "277132007", "Therapeutic procedure"));
Leider nochmal komplizierter:

![image](https://github.com/user-attachments/assets/3616a4d6-ec4d-4834-b25f-1cd5c466160c)

(https://simplifier.net/guide/mii-ig-modul-onkologie-2024-de/MIIIGModulOnkologie/TechnischeImplementierung/FHIR-Profile/Systemische-Therapie/Systemische-Therapie-Procedure.page.md?version=current)

2024-11-20 17:10 UTC, pcvolkmer commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/SystemischeTherapieMapper.java
> +      var performedStart = new DateTimeType();
Ich habe dazu zwei neue Methoden hinzugefügt, die ein `Optional` von `DateTimeType` zurück geben. Damit ist die Codierung im JSON entsprechend der erforderlichen oBDS-Genauigkeit:
* Einmal für `DatumTagOderMonatGenauTyp`
* und einmal für `XMLGregorianCalendar` -  da `getEnde()` diesen Datentyp zurück gibt.

2024-11-20 17:30 UTC, pcvolkmer commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/SystemischeTherapieMapper.java
> +                fhirProperties.getSystems().getSnomed(), "277132007", "Therapeutic procedure"));
Im oBDS v3 gibt es keine direkte Angabe zum SNOMED-CT, OPS nur für `OP_Typ`. Ich verwende daher `dataAbsentCode`.

2024-11-21 21:16 UTC, chgl requested changes

2024-11-21 21:16 UTC, chgl commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/SystemischeTherapieProcedureMapper.java
> +    code.addCoding().setSystem(fhirProperties.getSystems().getOps()).setCodeElement(dataAbsentCode);
Wir müssten es prinzipiell auch gar nicht setzen - OPS wird nicht erwartet, also sollte es reichen `mii-cs-onko-therapie-typ` zu setzen (falls syst.getTherapieart null, dann könnte man den code dafür noch auf absent setzen).

Ansonsten wäre hier noch das mapping von obds -> snomed: https://simplifier.net/guide/mii-ig-modul-onkologie-2024-de/MIIIGModulOnkologie/TechnischeImplementierung/oBDS-SNOMED-CT-Mapping/Therapietyp.page.md?version=current

Das und das mappen der Kategorie können wir aber auch in einem follow-up machen und erstmal als issue festhalten für die Zukunft.

2024-11-21 21:16 UTC, chgl commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/SystemischeTherapieProcedureMapper.java
> +    return procedure;
procedure.outcome wäre noch gut, ist zwar auch optional, aber die werte aus obds können 1:1 übernommen werden: https://simplifier.net/medizininformatikinitiative-modulonkologie/mii-cs-onko-therapie-ende-grund

2024-11-21 21:19 UTC, pcvolkmer commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/SystemischeTherapieProcedureMapper.java
> +    code.addCoding().setSystem(fhirProperties.getSystems().getOps()).setCodeElement(dataAbsentCode);
FHIR-Verifier hat gemeckert, wenn es nicht gesetzt war ... daher ist es mit drin.

2024-11-21 21:28 UTC, pcvolkmer commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/SystemischeTherapieProcedureMapper.java
> +    return procedure;
Baue ich ein. Dabei erst einmal für die 1:1-Mapping. Die möglichen Werte für

* R: reguläres Ende mit Dosisreduktion
* W: reguläres Ende mit Substanzwechsel

gibt es oBDS nicht und sollten daher nie gemappt werden.

2024-11-21 21:43 UTC, chgl commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/SystemischeTherapieProcedureMapper.java
> +    return procedure;
Wo siehst du das? In https://github.com/bzkf/obds-to-fhir/blob/beta/src/main/resources/schema/oBDS_v3.0.3.xsd#L5370-L5379 finde ich sie noch

2024-11-21 21:45 UTC, pcvolkmer commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/SystemischeTherapieProcedureMapper.java
> +    return procedure;
Ich war nicht in der letzten Version. In v3.0.3 ist es 1:1 entsprechend FHIR.

2024-11-21 21:46 UTC, chgl commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/SystemischeTherapieProcedureMapper.java
> +    code.addCoding().setSystem(fhirProperties.getSystems().getOps()).setCodeElement(dataAbsentCode);
Ja du hast absolut recht, man könnte jetzt von therapieart auf zumindest die OPS und snomed obergruppen mappen:

![image](https://github.com/user-attachments/assets/07e1367d-93c4-4189-9b4d-469dce9da4c9)

Aber auch etwas für den Nachgang.

Die Beispielresource im IG ist dann auch falsch an der stelle: https://simplifier.net/guide/mii-ig-modul-onkologie-2024-de/MIIIGModulOnkologie/TechnischeImplementierung/FHIR-Profile/Systemische-Therapie/Systemische-Therapie-Procedure.page.md?version=current - in den ganz neuen beispielresourcen in GitHub aber zumindest richtig: https://github.com/medizininformatik-initiative/kerndatensatzmodul-onkologie/blob/dev/fsh-generated/resources/Procedure-PatientKimMusterperson-SystemicTherapy-1.json#L49

2024-11-21 22:17 UTC, chgl approved these changes

2024-11-21 22:17 UTC, merged