feat: add initial SystemischeTherapieMedicationStatementMapper
bzkf/obds-to-fhir pull request #170
Opened 2024-11-22 11:41 UTC by pcvolkmer

2024-11-25 06:19 UTC, pcvolkmer commented
Implementierung mit Pflichtangaben. Erzeugt valide FHIR Ressourcen. Feedback erbeten.

2024-11-25 11:18 UTC, chgl requested changes

2024-11-25 11:18 UTC, chgl commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/SystemischeTherapieMedicationStatementMapper.java
> +          substanzId = substanz.getBezeichnung().replaceAll("[^A-Za-z0-9]", "");
Könnte man auch als `[^\W]` machen. aber so ists mMn auch leserlicher. Laufen wir Gefahr dass Umlaute, ß, etc in Medikationsnamen dann zu Konflikten der ID führen *könnten*?

2024-11-25 11:18 UTC, chgl commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/SystemischeTherapieMedicationStatementMapper.java
> +                .setSystem(fhirProperties.getSystems().getSystemischeTherapieProcedureId())
`getSystemischeTherapieProcedureId` müsste noch ein eigenes identifier-system sein

2024-11-25 11:18 UTC, chgl commented on src/main/resources/application.yml
> +    mii-pr-medication-statement: "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationStatement"
Ah! Dann sollte er korrekter validieren.
```suggestion
    mii-pr-medication-statement: "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-pr-onko-systemische-therapie-medikation"
```

2024-11-25 11:21 UTC, pcvolkmer commented on src/main/resources/application.yml
> +    mii-pr-medication-statement: "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationStatement"
Das baue ich ein

2024-11-25 12:19 UTC, pcvolkmer commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/SystemischeTherapieMedicationStatementMapper.java
> +          substanzId = substanz.getBezeichnung().replaceAll("[^A-Za-z0-9]", "");
Ich habe es nun so umgesetzt, dass `.replaceAll("[^A-Za-z0-9]+", "_")` zuzüglich der ersten 4 Chars des SHA256 Hashs ohne Replace verwendet wird. Dann kann es (praktisch) nur noch zu Kollisionen kommen, wenn Therapie-ID und Substanzname identisch sind.

2024-11-25 14:35 UTC, chgl approved these changes

2024-11-25 14:35 UTC, merged

2025-01-22 16:02 UTC, pcvolkmer commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/SystemischeTherapieMedicationStatementMapper.java
> +    var bundle = new Bundle();
Wir hatten uns für `List<>` ausgesprochen. Änderung wurde so umgesetzt.