feat: implement death mapping
bzkf/obds-to-fhir pull request #178
Opened 2024-11-25 23:14 UTC by BoehmDo

#127

2025-01-07 12:35 UTC, chgl requested changes

2025-01-07 12:35 UTC, chgl commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/TodMapper.java
> +    // Objects.requireNonNull(condition);
Kannst du analog zu https://github.com/bzkf/obds-to-fhir/pull/177/files#diff-02fe0f2219e5b30a6ca89eed91350aa6c971b0f69cd5bad07bc8567e50235ee0R20 als Parameter übergeben

2025-01-07 12:35 UTC, chgl commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/TodMapper.java
> +    observation.setFocus(focusList);
```suggestion
    observation.addFocus(condition);
```

Etwas kompakter

2025-01-07 12:35 UTC, chgl commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/TodMapper.java
> +      for (AllgemeinICDTyp todesursache :
Ich hatte mal mit @noemide rücksprache gehalten: es wäre eigentlich besser für jeden ICD-Code eine eigene Observation zu erzeugen, da eigentlich mehrere codeableconcepts mit dem gleichen code-system untypisch/falsch sind. Auch wenn die Wahrscheinlichkeit, dass sowieso mehr als 1 icd code gesetzt sind niedrig ist.

D.h. map() würde eine List<Observation> zurückgeben die sich dann nur im ICD-Code unterscheiden.

2025-01-07 12:35 UTC, chgl commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/TodMapper.java
> +  public Observation map(
Observation.id und Observation.identifier müssten noch gesetzt werden, sonst nur die Kleinigkeiten.

2025-01-07 12:35 UTC, chgl commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/TodMapper.java
> +            .setVersion(todesursache.getVersion());
das getVersion müsstest du noch parsen um auf nur das versionYear zu kommen, da idie FHIR code.version für icd 10 nur das Jahr beinhalten sollte.

2025-01-08 13:03 UTC, BoehmDo commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/TodMapper.java
> +      for (AllgemeinICDTyp todesursache :
Meinst du die ICD-Codes in eigene Observations auszulagern, oder für jede Todesursache eine duplizierte Tod Ressource zu erzeugen? Ich gehe jetzt erstmal von letzterem aus, nur dass ich das richtig verstanden habe.

2025-01-08 14:22 UTC, BoehmDo commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/TodMapper.java
> +  public Observation map(
Der identifier der Observations ist jetzt <Abschluss_id>_<icd-code>. Funktioniert natürlich, fühlt sich aber noch nicht so super elegant an, oder passt das?

2025-01-08 14:58 UTC, chgl commented on src/test/java/org/miracum/streams/ume/obdstofhir/mapper/mii/TodMapperTest.java
> +    var observListString = "[";
Du kannst den Code hieraus nehmen: das erzeugt dann eine resource pro eintrag in der liste - mit dem [] kommt sonst der fhir validator nicht zurecht

2025-01-08 15:05 UTC, chgl commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/TodMapper.java
> +  public Observation map(
ich finds erstmal OK so: aber ja, knifflige sache: was wenn nachträglich zB die Todesursache angepasst wird, dann hätten wir durch inkrementelles laden plötzlich 2, da sich die id ändert. Bei fernmetastasen hatten wir zB den index in der liste mit in die id gepackt: aber da das gleiche, wenn was wegkommt haben wir potentiell einen falschen  zustand. Ich nehm das noch als issue auf, aber gerne erstmal so lassen.

2025-01-08 15:06 UTC, chgl commented on src/test/java/snapshots/org/miracum/streams/ume/obdstofhir/mapper/mii/TodMapperTest.map_withGivenObds_shouldCreateValidProcedure.Testpatient_1.xml.approved.fhir.json
> +    "system": "https://bzkf.github.io/obds-to-fhir/identifiers/observation-id",
würde hier noch ein konkretes system nur für die tod-observations vorschlagen um kollisionen zu vermeiden:

`https://bzkf.github.io/obds-to-fhir/identifiers/tod-observation-id`

Ansonsten perfekt!

2025-01-08 17:38 UTC, chgl approved these changes

2025-01-08 17:40 UTC, merged