feat: initial ResidualstatusMapper
bzkf/obds-to-fhir pull request #180
Opened 2024-11-26 11:18 UTC by pcvolkmer

2024-12-11 10:04 UTC, pcvolkmer commented
Datum nur über Verwendung der OP möglich.

2025-01-07 14:06 UTC, chgl requested changes

2025-01-07 14:06 UTC, chgl commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/ResidualstatusMapper.java
> +  public Observation map(ResidualstatusTyp rs, Reference patient) {
Observation.id, .identifier, .focus sollten wir noch setzen, ansonsten passt alles!

2025-01-07 14:13 UTC, chgl commented
> Datum nur über Verwendung der OP möglich.

Macht es Sinn das Datum dann noch zu ergänzen?

2025-01-20 09:00 UTC, pcvolkmer commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/ResidualstatusMapper.java
> +  public Observation map(ResidualstatusTyp rs, Reference patient) {
Auch das ist nur über die Verwendung der OP möglich, da der Residualstatus selbst diese Information nicht enthält.

2025-01-20 09:01 UTC, pcvolkmer commented
> > Datum nur über Verwendung der OP möglich.
> 
> Macht es Sinn das Datum dann noch zu ergänzen?

Siehe: https://github.com/bzkf/obds-to-fhir/pull/180#issuecomment-2535379122

2025-01-20 09:01 UTC, pcvolkmer commented
> > Datum nur über Verwendung der OP möglich.
> 
> Macht es Sinn das Datum dann noch zu ergänzen?

Dann nur über Mapping der OP in Residualstatus

2025-01-20 12:00 UTC, pcvolkmer commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/ResidualstatusMapper.java
> +  public Observation map(ResidualstatusTyp rs, Reference patient) {
Über die OP könnte für jede OPS die ID bezogen werden und diese zusammengefasst für den Residualstatus verwendet werden:

```java
var identifiers =
    op.getMengeOPS().getOPS().stream()
        .map(
            ops ->
                new Identifier()
                    .setSystem(...)
                    .setValue(String.format("%s%s", op.getOPID(), ops.getCode())))
        .toList();
```

2025-01-20 12:36 UTC, chgl commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/ResidualstatusMapper.java
> +  public Observation map(ResidualstatusTyp rs, Reference patient) {
Ah okay, blöd, aber dann kommen wir da wohl doch nicht drum herum: OPTyp als Parameter um an id, identifier, effectiveDate zu kommen.

Am Ende haben wir pro OP Meldung nur einen Residualstatus, oder? - Würde es von daher nicht reichen die OP_ID direkt als identifier der Residualstatus Observation zu nutzen?

2025-01-20 14:45 UTC, chgl requested changes

2025-01-20 14:45 UTC, chgl commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/ResidualstatusMapper.java
> +  public Observation map(OPTyp op, Reference patient) {
```suggestion
  public Observation map(OPTyp op, Reference patient, Reference condition) {
```

Analog zu https://github.com/bzkf/obds-to-fhir/pull/155/files#diff-19bc8d016f948222434927e3db9fea3f15c323943ade9788771de3395c00e4eeR26 kannst du noch die condition reference als parameter übergen und dann Observation.focus darauf setzen - Die Condition-reference baut dann der obds-to-bundle-mapper in: https://github.com/bzkf/obds-to-fhir/pull/173/files#diff-4f8b08222492b7285cffcddf0cdd63b7390d737af96125e170490c284352c6afR120-R121. Dann ist's perfekt :)

2025-01-20 14:55 UTC, pcvolkmer commented on src/main/java/org/miracum/streams/ume/obdstofhir/mapper/mii/ResidualstatusMapper.java
> +  public Observation map(OPTyp op, Reference patient) {
Alles schon erledigt, allerdings mit Parameternamen `focus` ;)

2025-01-20 15:29 UTC, chgl approved these changes

2025-01-20 15:30 UTC, merged